theme = "soho"
baseurl = "/"
languageCode = "en-uk"
title = "Roberto Villegas-Diaz"
DefaultContentLanguage = "en-uk"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.qmd$", "\\.ipynb$", "\\.py$"]
googleAnalytics = "UA-168074535-1"

[params]
title = "Roberto Villegas-Diaz"
author = "Roberto Villegas-Diaz"
# description = "Example Blog"
# gravatar = "soho@example.com"
images = ["images/roberto.jpg"]
profilePicture = "images/roberto.jpg"
copyright = "Roberto Villegas-Diaz"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["presentations", "post"]

## Set custom theme color.
themeColor = "#15446f"

[permalinks]
post = "/:year/:month/:day/:slug/"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/roberto-villegas-diaz/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/villegar/"
  
  [[params.socialIcons]]
  icon = "fa-researchgate"
  title = "ResearchGate"
  url = "https://www.researchgate.net/profile/Roberto-Villegas-Diaz"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://www.twitter.com/r_villegas_diaz"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/posts/"
  
  [[menu.main]]		
  name = "Presentations"		
  weight = 3		
  identifier = "presentations"		
  url = "/presentations/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"
  
  #[[menu.main]]
  #name = "CV"
  #identifier = "cv"
  #weight = 15
  #url = "/vitae/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.goldmark.renderer]
  unsafe= true